# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command Allstock.create(or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([( name 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Item.destroy_all
SavingPot.destroy_all
Transaction.destroy_all
Allstock.destroy_all
User.destroy_all



# ---------------------Users-------------------------------------------

user1 = User.create(username: "Elle", password: "123456", balance: 100000)
user2 =User.create(username: "Leah", password: "123456", balance: 100000)
user3 =User.create(username: "Ranya", password: "123456", balance: 100000)
user4 =User.create(username: "Tom", password: "123456", balance: 100000)
user5 =User.create(username: "Ben", password: "123456", balance: 100000)


# ---------------------pots-------------------------------------------
# Item.create(name: 'Postion', description: 'lalalal', user_id: user1.id )
# Item.create(name: 'HEllo', description: 'heheh', user_id: user2.id )

#-----------------Transactions------------------------------------------




Transaction.create(date: "2019-01-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"BT Gas", amount: 600, spendingSection: "subscriptions", user_id: user2.id )
Transaction.create(date: "2019-01-01", company:"British Airways", amount: 100, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"Virgin", amount: 300, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"M&S", amount: 50, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-01-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 5, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 40, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2019-01-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-01-01", company:"British Airways", amount: 10, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"Virgin", amount: 300, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-01-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 6, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2019-01-01", company:"TFL", amount: 25, spendingSection: "other", user_id: user2.id )


Transaction.create(date: "2019-02-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-02-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"Virgin", amount: 300, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-02-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 5, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 40, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2019-02-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-02-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"Virgin", amount: 300, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-02-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 6, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 40, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2019-02-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2019-03-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-03-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"Virgin", amount: 300, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-03-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2019-03-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-03-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"M&S", amount: 50, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-03-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 40, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2019-03-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2019-04-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-04-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-04-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2019-04-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-04-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-04-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 5, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-04-01", company:"TFL", amount: 25, spendingSection: "phone", user_id: user2.id )

Transaction.create(date: "2019-05-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-05-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-05-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2019-05-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-05-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-05-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 6, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-05-01", company:"TFL", amount: 25, spendingSection: "phone", user_id: user2.id )

Transaction.create(date: "2019-06-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-06-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-06-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 25, spendingSection: "other", user_id: user2.id )
Transaction.create(date: "2019-06-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-06-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-06-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-06-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2019-07-01", company:"Sky", amount: 100, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-07-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-07-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 40, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2019-07-01", company:"Sky", amount: 100, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"BT Gas", amount: 600, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2019-07-01", company:"British Airways", amount: 100, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2019-07-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2019-07-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

#-------------- 2018 ------------------

Transaction.create(date: "2018-01-01", company:"Sky", amount: 10, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"BT Gas", amount: 60, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-01-01", company:"British Airways", amount: 10, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"Tesco", amount: 40, spendingSection: "other", user_id: user2.id )
Transaction.create(date: "2018-01-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 6, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 40, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-01-01", company:"Sky", amount: 10, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"BT Gas", amount: 60, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-01-01", company:"British Airways", amount: 10, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-01-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-01-01", company:"TFL", amount: 25, spendingSection: "phone", user_id: user2.id )

Transaction.create(date: "2018-02-01", company:"Sky", amount: 1, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-02-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"Virgin", amount: 3, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"Tesco", amount: 40, spendingSection: "other", user_id: user2.id )
Transaction.create(date: "2018-02-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-02-01", company:"Sky", amount: 1, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-02-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"Virgin", amount: 3, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-02-01", company:"Nandos", amount: 60, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 6, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 40, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-02-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-03-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-03-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"Virgin", amount: 3, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-03-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 5, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 40, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-03-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-03-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"Virgin", amount: 30, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-03-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 6, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-03-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-04-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-04-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-04-01", company:"Nandos", amount: 60, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-04-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-04-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"M&S", amount: 50, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-04-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 6, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-04-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-05-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-05-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-05-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 25, spendingSection: "other", user_id: user2.id )
Transaction.create(date: "2018-05-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-05-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"Virgin", amount: 30, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"Tesco", amount: 40, spendingSection: "phone", user_id: user2.id )
Transaction.create(date: "2018-05-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 5, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-05-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-06-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-06-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-06-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 25, spendingSection: "phone", user_id: user2.id )
Transaction.create(date: "2018-06-01", company:"Sky", amount: 1, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-06-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-06-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 5, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 6, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-06-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-07-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-07-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-07-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 40, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 25, spendingSection: "other", user_id: user2.id )
Transaction.create(date: "2018-07-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-07-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-07-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 6, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-07-01", company:"TFL", amount: 25, spendingSection: "phone", user_id: user2.id )

Transaction.create(date: "2018-08-01", company:"Sky", amount: 10, spendingSection: "subscriptions", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-08-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"Virgin", amount: 3, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-08-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-08-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-08-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-08-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 50, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 60, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-08-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-09-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-09-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"Virgin", amount: 3, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-09-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 50, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 60, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 4, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-09-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-09-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"M&S", amount: 50, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"Tesco", amount: 40, spendingSection: "other", user_id: user2.id )
Transaction.create(date: "2018-09-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 5, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 40, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-09-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-10-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-10-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-10-01", company:"Nandos", amount: 60, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 5, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 40, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-10-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-10-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-10-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 6, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-10-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )

Transaction.create(date: "2018-11-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-11-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-11-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 5, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 6, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-11-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-11-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"M&S", amount: 50, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"Tesco", amount: 40, spendingSection: "other", user_id: user2.id )
Transaction.create(date: "2018-11-01", company:"Nandos", amount: 60, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 5, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 40, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-11-01", company:"TFL", amount: 25, spendingSection: "phone", user_id: user2.id )

Transaction.create(date: "2018-12-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-12-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-12-01", company:"Nandos", amount: 60, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 5, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 6, spendingSection: "tech", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 40, spendingSection: "retail", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 25, spendingSection: "travel", user_id: user2.id )
Transaction.create(date: "2018-12-01", company:"Sky", amount: 1, spendingSection: "subscriptions",user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"BT Gas", amount: 6, spendingSection: "bills", user_id: user2.id )
Transaction.create(date: "2018-12-01", company:"British Airways", amount: 1, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"Virgin", amount: 30, spendingSection: "holiday", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"M&S", amount: 50, spendingSection: "food", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"Tesco", amount: 40, spendingSection: "food", user_id: user2.id )
Transaction.create(date: "2018-12-01", company:"Nandos", amount: 60, spendingSection: "phone", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 5, spendingSection: "travel", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 6, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 40, spendingSection: "other", user_id: user1.id )
Transaction.create(date: "2018-12-01", company:"TFL", amount: 25, spendingSection: "tech", user_id: user2.id )


#------------------------------------------------------------------------------------------------
#Saving Pot

SavingPot.create(name: "Car", description:"4 door car.", date:"12/12/2020", goal: 3, user_id: user2.id )
SavingPot.create(name: "Wedding", description:"4 door car.", date:"12/12/2020", goal: 3, user_id: user2.id )
SavingPot.create(name: "Dog", description:"4 door car.", date:"12/12/2020", goal: 3, user_id: user2.id )
SavingPot.create(name: "Shoes", description:"4 door car.", date:"12/12/2020", goal: 2, user_id: user2.id )
SavingPot.create(name: "Dog", description:"4 door car.", date:"12/12/2020", goal: 1, user_id: user2.id )
SavingPot.create(name: "Belt", description:"4 door car.", date:"12/12/2020", goal: 40, user_id: user2.id )
SavingPot.create(name: "Wedding", description:"4 door car.", date:"12/12/2020", goal: 3, user_id: user1.id )
SavingPot.create(name: "Bag", description:"4 door car.", date:"12/12/2020", goal: 2, user_id: user1.id )
SavingPot.create(name: "Phone", description:"4 door car.", date:"12/12/2020", goal: 10, user_id: user1.id )
SavingPot.create(name: "Food", description:"4 door car.", date:"12/12/2020", goal: 3, user_id: user1.id )
SavingPot.create(name: "Drink", description:"4 door car.", date:"12/12/2020", goal: 1, user_id: user1.id )
SavingPot.create(name: "Laptop", description:"4 door car.", date:"12/12/2020", goal: 20, user_id: user1.id )
SavingPot.create(name: "Ipad", description:"4 door car.", date:"12/12/2020", goal: 10, user_id: user1.id )
SavingPot.create(name: "Airpods", description:"4 door car.", date:"12/12/2020", goal: 2, user_id: user1.id )


#----------------------------------------------------------
#all stocks 


    s1=Allstock.create(ticker:"GOOG", name: "Google", sector: "Tech", price: 1194.80) 
    s2=Allstock.create(ticker: "FB", name: "Facebook", sector: "Tech", price: 168.85)
    s3=Allstock.create(ticker: "TWTR", name: "Twitter", sector: "Tech", price: 29.41)
    s4=Allstock.create(ticker: "AMZN", name: "Amazon", sector: "Tech", price: 2013.04)
    s5=Allstock.create(ticker: "V", name: "Visa", sector: "Finance", price: 150.05)
    s6=Allstock.create(ticker: "BAC", name: "Bank of America", sector: "Finance", price: 29.95)
    s7=Allstock.create(ticker: "JPM", name: "JP Morgan", sector: "Finance", price: 114.45)
    s8=Allstock.create(ticker: "C", name: "Citi Bank", sector: "Finance", price: 72.94)
    s9=Allstock.create(ticker: "NKE", name: "Nike", sector: "Sportswear", price: 84.56)
    s10=Allstock.create(ticker: "UAA", name: "Under Armour", sector: "Sportswear", price: 21.07)
